### ISSUE TITLE
Package does not support current version of factory-girl

### ISSUE THREAD

**Issue by renanmzmendes** [simonexmachina/factory-girl-sequelize#8]
I don't know if this package is still maintained, but assuming it is, it does not support `factory-girl`s current version, being stuck in v3.

I'm getting the following error when requiring `factory-girl-sequelize`:

```
SequelizeAdapter.prototype = new Adapter();
                             ^

TypeError: Adapter is not a constructor
```

My related dependencies:

```
    "pg": "^7.3.0",
    "sequelize": "^4.18.0",
    "factory-girl": "^4.3.0",
    "factory-girl-sequelize": "^1.0.1",
```

**Comment by aexmachina** [comment]
Yes, this module is now included in the current version of factory-girl and is deprecated. I'll update the module to indicate this.
